import { FolderCodeIcon, HomeIcon, PenBoxIcon } from 'lucide-react';
import { Nav, NavItem } from '@/components/nav';
import { NavSearch, NavSearchPanel } from '@/components/nav/index';
import "./globals.css";
import { ThemeProvider } from 'next-themes'
import { Rays } from '@/components/header/rays';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className='bg-background w-full min-h-screen'>
				<Rays className="w-full min-w-7xl -top-1/2 bg-center h-screen fixed opacity-50 pointer-events-none" />
				<ThemeProvider attribute={'class'}>
					<Nav>
						<NavItem label="Home" href="/">
							<HomeIcon className="size-4" />
						</NavItem>
						<NavItem label="Notes" href="/notes">
							<PenBoxIcon className="size-4" />
						</NavItem>
						<NavItem label="Projects" href="/projects">
							<FolderCodeIcon className="size-4" />
						</NavItem>
						<NavSearch />
						<NavSearchPanel />
					</Nav>

					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
