import { FolderCodeIcon, HomeIcon, PenBoxIcon } from 'lucide-react';
import { Nav, NavItem } from '@/components/nav';
import { NavSearch, NavSearchPanel } from '@/components/nav/index';
import "./globals.css";
import { ThemeProvider } from 'next-themes'
import { Rays } from '@/components/header/rays';
import Footer from '@/components/footer/index';
import { GeistSans } from "geist/font/sans";
import { cn } from '@/lib/utils';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn(GeistSans.className, 'bg-background w-full min-h-screen')}>
				<Rays className="w-full min-w-7xl -top-1/2 bg-center h-screen fixed opacity-50 pointer-events-none -z-1" />
				{/* TOP PROGRESSIVE BLUR */}
				{/* <div
					className="w-full h-20 -top-5 left-0 fixed pointer-events-none z-40"
					style={{
						mask: 'linear-gradient(black, black, transparent)',
						backdropFilter: 'blur(4px) saturate(180%)',
					}}
				/> */}

				{/* DOTTED GRID MESH GRADIENT */}
				{/* <div
					style={{
						backgroundColor: 'transparent',
						backgroundImage: 'radial-gradient(transparent 1px, var(--background, #ffffff) 1px)',
						backgroundSize: '4px 4px',
						backdropFilter: 'blur(3px)',
						WebkitBackdropFilter: 'blur(3px)',
						mask: 'linear-gradient(rgb(0, 0, 0) 30%, rgba(0, 0, 0, 0) 95%, transparent 100%)',
						maskSize: 'auto',
						maskComposite: 'add',
						maskMode: 'match-source',
						opacity: 1,
					}}
					className='fixed top-0 left-0 w-full h-[100px] z-10 pointer-events-none'
				/> */}

				<div
					className="w-full h-[100px] bottom-0 fixed pointer-events-none z-40"
					style={{
						mask: 'linear-gradient(transparent, black, black)',
						backdropFilter: 'blur(4px) saturate(180%)',
					}}
				/>
				<ThemeProvider attribute={'class'}>
					<Nav>
						<NavItem label="Home" href="/">
							<HomeIcon className="size-4" />
						</NavItem>
						<NavItem label="Notes" href="/notes">
							<PenBoxIcon className="size-4" />
						</NavItem>
						<NavItem label="Projects" href="/projects">
							<FolderCodeIcon className="size-4" />
						</NavItem>
						<NavSearch />
						<NavSearchPanel />
					</Nav>

					{children}

					<Footer />
				</ThemeProvider>
			</body>
		</html>
	)
}
